INSERT INTO Movies (Id,Title) VALUES (2,'The Big Lebowski');
INSERT INTO Movies (Id,Title) VALUES (3,'Shrek 1');
INSERT INTO Movies (Id,Title) VALUES (4,'Reefer Madness');
INSERT INTO Movies (Id,Title) VALUES (5,'Avatar');
INSERT INTO Movies (Id,Title) VALUES (6,'Eternal Sunshine of the Spotless Mind');
INSERT INTO Movies (Id,Title) VALUES (7,'Fern Gully');
INSERT INTO Movies (Id,Title) VALUES (8,'Aladdin');
INSERT INTO Movies (Id,Title) VALUES (9,'Lion King');
INSERT INTO Movies (Id,Title) VALUES (10,'Clue');
INSERT INTO Movies (Id,Title) VALUES (11,'Good Morning Vietnam');
INSERT INTO Movies (Id,Title) VALUES (12,'Groundhog Day');
INSERT INTO Movies (Id,Title) VALUES (13,'Memento');
INSERT INTO Movies (Id,Title) VALUES (14,'Bill and Ted''s Excellent Adventure');
INSERT INTO Movies (Id,Title) VALUES (15,'Speed');
INSERT INTO Movies (Id,Title) VALUES (16,'Blues Brothers');
INSERT INTO Movies (Id,Title) VALUES (17,'Breakfast Club');
INSERT INTO Movies (Id,Title) VALUES (18,'Star Wars');
INSERT INTO Movies (Id,Title) VALUES (19,'India Jones');
INSERT INTO Movies (Id,Title) VALUES (20,'Lawrence of Arabia');
INSERT INTO Movies (Id,Title) VALUES (22,'Ferris Buehller''s Day Off');
INSERT INTO Movies (Id,Title) VALUES (23,'Forest Gump');
INSERT INTO Movies (Id,Title) VALUES (24,'Pirates of the Carribean: Curse of the Black Pearl');
INSERT INTO Movies (Id,Title) VALUES (25,'Jaws');
INSERT INTO Movies (Id,Title) VALUES (26,'Finding Nemo');
INSERT INTO Movies (Id,Title) VALUES (27,'Blazing Saddles');
INSERT INTO Movies (Id,Title) VALUES (28,'Toy Story');
INSERT INTO Movies (Id,Title) VALUES (29,'Groundhog Day');
INSERT INTO Movies (Id,Title) VALUES (30,'Monty Python and the HOly Grail');
INSERT INTO Movies (Id,Title) VALUES (31,'WallE ');
INSERT INTO Movies (Id,Title) VALUES (32,'2001');
INSERT INTO Movies (Id,Title) VALUES (33,'High Fidelity');
INSERT INTO Movies (Id,Title) VALUES (34,'Pewee''s Big Adventure');
INSERT INTO Movies (Id,Title) VALUES (35,'Beetlejuice');
INSERT INTO Movies (Id,Title) VALUES (36,'Dazed and Confused');
INSERT INTO Movies (Id,Title) VALUES (37,'Ghostbusters');
INSERT INTO Movies (Id,Title) VALUES (38,'Independence Day');
INSERT INTO Movies (Id,Title) VALUES (39,'The Godfather');
INSERT INTO Movies (Id,Title) VALUES (40,'Donnie Darko');
INSERT INTO Movies (Id,Title) VALUES (41,'Fight Club');
INSERT INTO Movies (Id,Title) VALUES (42,'Interview with a Vampire');
INSERT INTO Movies (Id,Title) VALUES (43,'Blade Runner');
INSERT INTO Movies (Id,Title) VALUES (44,'The Neverending Story');
INSERT INTO Movies (Id,Title) VALUES (45,'Space Balls');
INSERT INTO Movies (Id,Title) VALUES (46,'Man in Tights');
INSERT INTO Movies (Id,Title) VALUES (47,'History of the World part 1');
INSERT INTO Movies (Id,Title) VALUES (48,'Young Frakenstein');
INSERT INTO Movies (Id,Title) VALUES (49,'Mighty Ducks');
INSERT INTO Movies (Id,Title) VALUES (50,'The Labyrinth');
INSERT INTO Movies (Id,Title) VALUES (51,'Treasure Planet');
INSERT INTO Movies (Id,Title) VALUES (52,'Titan AE');
INSERT INTO Movies (Id,Title) VALUES (53,'Michael Keaton Batman');
INSERT INTO Movies (Id,Title) VALUES (54,'Val Kilmer Batman');
INSERT INTO Movies (Id,Title) VALUES (55,'Raising Arizona');
INSERT INTO Movies (Id,Title) VALUES (56,'O Brother Where Art Thou');
INSERT INTO Movies (Id,Title) VALUES (57,'Citizen Kane');
INSERT INTO Movies (Id,Title) VALUES (58,'The Graduate');
INSERT INTO Movies (Id,Title) VALUES (59,'Goodwill Hunting');
INSERT INTO Movies (Id,Title) VALUES (60,'Animal House');
INSERT INTO Movies (Id,Title) VALUES (61,'Planet of the Apes');
INSERT INTO Movies (Id,Title) VALUES (62,'Dune');
INSERT INTO Movies (Id,Title) VALUES (63,'Pulp Fiction');
INSERT INTO Movies (Id,Title) VALUES (64,'Kill Bill');
INSERT INTO Movies (Id,Title) VALUES (65,'Best in Show');
INSERT INTO Movies (Id,Title) VALUES (66,'Tron');
INSERT INTO Movies (Id,Title) VALUES (67,'Who Framed Roger Rabbit');
INSERT INTO Movies (Id,Title) VALUES (68,'Starship troopers');
INSERT INTO Movies (Id,Title) VALUES (69,'Rocky Horror Picture Show');
INSERT INTO Movies (Id,Title) VALUES (70,'Dark Crystal');
INSERT INTO Movies (Id,Title) VALUES (71,'Ballad of Ricky Bobby');
INSERT INTO Movies (Id,Title) VALUES (72,'Space Jam');
INSERT INTO Movies (Id,Title) VALUES (73,'Pink Floyd''s The Wall');
INSERT INTO Movies (Id,Title) VALUES (74,'The Matrix');
INSERT INTO Movies (Id,Title) VALUES (75,'Diehard');
INSERT INTO Movies (Id,Title) VALUES (76,'Moulin Rouge');
INSERT INTO Movies (Id,Title) VALUES (77,'The Hangover');
INSERT INTO Movies (Id,Title) VALUES (78,'There''s Something about Mary');
INSERT INTO Movies (Id,Title) VALUES (79,'Accepted');
INSERT INTO Movies (Id,Title) VALUES (80,'Wayne''s World');
INSERT INTO Movies (Id,Title) VALUES (81,'Condheads');
INSERT INTO Movies (Id,Title) VALUES (82,'James Bond');
INSERT INTO Movies (Id,Title) VALUES (83,'Austin Powers');
INSERT INTO Movies (Id,Title) VALUES (84,'Clerks');
INSERT INTO Movies (Id,Title) VALUES (85,'Mall Rats');
INSERT INTO Movies (Id,Title) VALUES (86,'Reservoir Dogs');
INSERT INTO Movies (Id,Title) VALUES (87,'Fargo');
INSERT INTO Movies (Id,Title) VALUES (88,'Boondock Saints');
INSERT INTO Movies (Id,Title) VALUES (89,'2001: Space Odyssey');
INSERT INTO Movies (Id,Title) VALUES (90,'The producers and the bird cage');
INSERT INTO Movies (Id,Title) VALUES (91,'Bad boys');
INSERT INTO Movies (Id,Title) VALUES (92,'Men in black');
INSERT INTO Movies (Id,Title) VALUES (93,'Coming to America');
INSERT INTO Movies (Id,Title) VALUES (94,'Training Day');
INSERT INTO Movies (Id,Title) VALUES (95,'Oceans Eleven');